import mysql.connector
import pandas as pd
import numpy as np
import tkinter as tk
from tkinter import Tk
from tkinter.filedialog import askopenfilename
from tkinter import messagebox

#pooling out the "parts" database from punk/vorelec
cnx = mysql.connector.connect(user='web-user', password='jump0ff',
                              host='192.168.254.62',
                              database='vorelec')
cursor = cnx.cursor()  
query = ("SELECT pn, description, manufacturer, manufpn, form, mount form FROM master")
cursor.execute(query)
PN = []
Desc = []
Manufacturer = []
Manufpn = []
Case = []
Mount = []
for (pn, description, manufacturer, manufpn, form, mount) in cursor:
    PN.append(pn)
    Desc.append(description)
    Manufacturer.append(manufacturer)
    Manufpn.append(manufpn)
    Case.append(form)
    Mount.append(mount)
cnx.close()


Parts_from_db = pd.DataFrame([PN,Desc,Manufacturer,Manufpn,Case, Mount]).transpose()
Parts_from_db.columns = ['PN','Desc','Manufacturer','Manufpn','Case', 'Mount']
Parts_from_db = Parts_from_db.set_index ('PN')



#getting BOM file generated by Kicad with our vorelec plugin

root = Tk()
root.withdraw() # we don't want a full GUI, so keep the root window from appearing
root.lift()
path_to_kicad_generated_bom_csv = askopenfilename(filetypes=[("CSV Files",".csv")]) # show an "Open" dialog box and return the path to the selected file

KiCad_BOM = pd.read_csv(path_to_kicad_generated_bom_csv)
KiCad_BOM = KiCad_BOM.reindex(columns = KiCad_BOM.columns.tolist() + ['Manufacturer'
                                                                      ,'Manufacturer Part Number'                                                                                                                                      ,'Description'
                                                                     , 'Package / Case'
                                                                     ,'SMD ,BGA,LLC(QFN),OR  TH'])

#filling missing fields in BOM from Parts database, based on common PN
for indx in range (KiCad_BOM.shape[0]):
    pn_of_group = KiCad_BOM.loc[indx]['PN']
    DNI = KiCad_BOM.loc[indx]['DNI']
    if (str(DNI)!='DNI'):
        if str(pn_of_group)=='nan':
            #message "not all pns are filled!"
            messagebox.showinfo("Error","not all PNs are filled!")
            break
        KiCad_BOM.loc[indx,'Manufacturer'] = Parts_from_db.loc[pn_of_group, 'Manufacturer']
        KiCad_BOM.loc[indx,'Manufacturer Part Number'] = Parts_from_db.loc[pn_of_group, 'Manufpn']
        KiCad_BOM.loc[indx,'Package / Case'] = Parts_from_db.loc[pn_of_group, 'Case']
        KiCad_BOM.loc[indx,'Description'] = Parts_from_db.loc[pn_of_group, 'Desc']
        KiCad_BOM.loc[indx,'SMD ,BGA,LLC(QFN),OR  TH'] = Parts_from_db.loc[pn_of_group, 'Mount']

KiCad_BOM = KiCad_BOM.sort_values(by=['PN'], ascending=True)

KiCad_BOM_DNI = KiCad_BOM[KiCad_BOM['DNI']=='DNI']
KiCad_BOM = KiCad_BOM.drop (KiCad_BOM[KiCad_BOM['DNI']=='DNI'].index)
KiCad_BOM = KiCad_BOM.append(KiCad_BOM_DNI).reset_index(drop=True)


KiCad_BOM['Item'] = range (KiCad_BOM.shape[0])
KiCad_BOM['Item']=KiCad_BOM['Item']+1


#final formatting/polishing
BOM_to_save = KiCad_BOM[['Item', 'PN','Manufacturer'
                         , 'Manufacturer Part Number', 'Designator'
                         , 'Qnty', 'Description', 'Package / Case'
                         , 'SMD ,BGA,LLC(QFN),OR  TH']]
cut_it = path_to_kicad_generated_bom_csv[::-1].find('/') #where the filename starts
our_directory = path_to_kicad_generated_bom_csv[:-cut_it] #folder with csv
path_to_final_BOM_xlsx = our_directory+'BOM_vorelec.xlsx'


xlsx_writer = pd.ExcelWriter(path_to_final_BOM_xlsx, engine='xlsxwriter')

BOM_to_save.to_excel(xlsx_writer, sheet_name='Sheet1', index=False)
wb = xlsx_writer.book
ws = xlsx_writer.sheets['Sheet1']

common_format = wb.add_format({'align': 'center', 'valign': 'vcenter'})

ws.set_column('A:A', 5, common_format) #Item
ws.set_column('B:B', 15, common_format) #Manuf
ws.set_column('C:D', 25, common_format) #Manuf part numb and Designator
ws.set_column('E:E', 5, common_format) #Qnty
ws.set_column('F:F', 35, common_format) #descript
ws.set_column('G:G', 15, common_format) #case
ws.set_column('H:H', 25, common_format) #SMD

xlsx_writer.save()

